#!/bin/sh -e

cd phpMyAdmin-5.0.4-all-languages

mkdir -p "$1/usr/share/webapps/phpmyadmin"
mkdir -p "$1/etc/phpmyadmin"
mkdir -p "$1/usr/share/phpmyadmin"

cp -r ./* "$1/usr/share/webapps/phpmyadmin/"

install -Dm664 config.sample.inc.php "$1/etc/phpmyadmin/config.inc.php"
install -Dm644 ../phpmyadmin.apache2.conf "$1/etc/apache2/conf.d/phpmyadmin.conf"

ln -sf /etc/phpmyadmin/config.inc.php "$1/usr/share/webapps/phpmyadmin/config.inc.php"
