#!/bin/sh -e

cat <<EOF

phpmyadmin has been installed to:
->    /usr/share/webapps/phpmyadmin

phpmyadmin config file has been installed to:
->   /etc/phpmyadmin/config.inc.php

If you use apache2:
1) Change the ownership of the config directory:
->    chown -R apache:apache /etc/phpmyadmin

2) See if you need to modify the apache2 config
->    /etc/apache2/conf.d/phpmyadmin.conf

3) Restart apache2 when done.

EOF
