#!/bin/sh -e

export PYTHON=/usr/bin/python3

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --disable-ldap \
    --with-libedit-preferred \
    --with-openssl \
    --with-uuid=e2fs \
    --disable-rpath \
    --with-llvm \
    --without-perl \
    --with-python \
    --without-icu \
    --without-tcl

make world
make DESTDIR="$1" install
