#!/bin/sh -e

autoreconf -vif

./configure \
    --build=$CBUILD \
    --host=$CHOST \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --without-libxml2 \
    --without-neverbleed \
    --without-jemalloc \
    --disable-python-bindings \
    --disable-examples \
    --enable-static \
    --enable-app \
    --without-libcares \
    --without-systemd \
    --without-jansson

make
make DESTDIR="$1" install
